from __future__ import annotations

from .models import SourceMetadata


SOURCES: dict[str, SourceMetadata] = {
    "bcb_sgs": SourceMetadata(
        source_id="bcb_sgs",
        name="Banco Central do Brasil - SGS",
        base_url="https://api.bcb.gov.br/dados/serie/",
        license_name="Dados Abertos BCB",
        update_frequency="daily",
        notes="Series macroeconomicas em JSON.",
    ),
    "bcb_ptax": SourceMetadata(
        source_id="bcb_ptax",
        name="Banco Central do Brasil - PTAX",
        base_url="https://olinda.bcb.gov.br/olinda/servico/PTAX/versao/v1/odata/",
        license_name="Dados Abertos BCB",
        update_frequency="daily",
        notes="Cotacoes oficiais de cambio via OData.",
    ),
    "bcb_focus": SourceMetadata(
        source_id="bcb_focus",
        name="Banco Central do Brasil - Focus",
        base_url="https://olinda.bcb.gov.br/olinda/servico/Expectativas/versao/v1/odata/",
        license_name="Dados Abertos BCB",
        update_frequency="weekly",
        notes="Expectativas de mercado para indicadores macro.",
    ),
    "cvm_dados_abertos": SourceMetadata(
        source_id="cvm_dados_abertos",
        name="CVM Dados Abertos",
        base_url="https://dados.cvm.gov.br/",
        license_name="ODbL",
        update_frequency="daily",
        notes="Companhias abertas, fundos, FIIs e carteiras.",
    ),
    "b3_cotahist": SourceMetadata(
        source_id="b3_cotahist",
        name="B3 COTAHIST Historico",
        base_url="https://bvmf.bmfbovespa.com.br/InstDados/SerHist/",
        license_name="Termos B3 Market Data",
        update_frequency="daily",
        notes="Historico D-1; sem intraday ou tempo real.",
    ),
    "b3_derivatives": SourceMetadata(
        source_id="b3_derivatives",
        name="B3 Derivativos - Dados Historicos",
        base_url="https://www.b3.com.br/pt_br/market-data-e-indices/servicos-de-dados/market-data/historico/",
        license_name="Termos B3 Market Data",
        update_frequency="daily",
        notes="Ajustes do pregao, resumo estatistico e boletins para derivativos listados.",
    ),
    "anbima_curves": SourceMetadata(
        source_id="anbima_curves",
        name="ANBIMA Feed - Curvas de Juros",
        base_url="https://api.anbima.com.br/feed/precos-indices/v1/titulos-publicos/curvas-juros",
        license_name="Termos ANBIMA Feed",
        update_frequency="daily",
        notes="ETTJ prefixada, IPCA e inflacao implicita; acesso conforme autenticacao e termos ANBIMA.",
    ),
    "tesouro_transparente": SourceMetadata(
        source_id="tesouro_transparente",
        name="Tesouro Transparente",
        base_url="https://www.tesourotransparente.gov.br/ckan/",
        license_name="ODbL",
        update_frequency="daily",
        notes="Taxas e precos do Tesouro Direto.",
    ),
    "ibge_sidra": SourceMetadata(
        source_id="ibge_sidra",
        name="IBGE SIDRA",
        base_url="https://apisidra.ibge.gov.br/values/",
        license_name="Dados Abertos IBGE",
        update_frequency="monthly",
        notes="Series socioeconomicas e territoriais.",
    ),
    "ipeadata": SourceMetadata(
        source_id="ipeadata",
        name="IPEADATA API",
        base_url="http://www.ipeadata.gov.br/api/odata4/",
        license_name="Uso publico com citacao da fonte",
        update_frequency="daily",
        notes="Series macro, regionais e sociais via OData.",
    ),
    "receita_cnpj": SourceMetadata(
        source_id="receita_cnpj",
        name="Receita Federal - CNPJ Dados Publicos",
        base_url="https://arquivos.receitafederal.gov.br/dados/cnpj/dados_abertos_cnpj/",
        license_name="Dados Abertos Receita Federal",
        update_frequency="monthly",
        notes="Arquivos grandes mensais; requer indexacao local SQLite.",
    ),
    "mdic_comex_stat": SourceMetadata(
        source_id="mdic_comex_stat",
        name="MDIC Comex Stat - Base Bruta",
        base_url="https://balanca.economia.gov.br/balanca/bd/comexstat-bd/",
        license_name="Dados Abertos MDIC",
        update_frequency="monthly",
        notes="CSVs anuais de exportacao/importacao por NCM e municipio.",
    ),
    "bndes_dados_abertos": SourceMetadata(
        source_id="bndes_dados_abertos",
        name="BNDES Dados Abertos",
        base_url="https://dadosabertos.bndes.gov.br/api/3/action/",
        license_name="ODbL",
        update_frequency="monthly",
        notes="Portal CKAN; recursos CSV com encoding windows-1252 ou latin-1.",
    ),
    "asset_master": SourceMetadata(
        source_id="asset_master",
        name="DadosBR Cadastro Mestre de Ativos",
        base_url="local://dadosbr/asset-master",
        license_name="Derived from official source licenses",
        update_frequency="ad_hoc",
        notes="Camada canonica derivada de B3, CVM, Receita, Tesouro, MDIC e BNDES.",
    ),
    "timeseries": SourceMetadata(
        source_id="timeseries",
        name="DadosBR Series Historicas Canonicas",
        base_url="local://dadosbr/timeseries",
        license_name="Derived from official source licenses; optional yfinance terms apply",
        update_frequency="ad_hoc",
        notes="Camada derivada para OHLCV, indicadores economicos, retornos e storage local.",
    ),
    "benchmarks": SourceMetadata(
        source_id="benchmarks",
        name="DadosBR Benchmarks e Macro",
        base_url="local://dadosbr/benchmarks",
        license_name="Derived from official source licenses; optional yfinance terms apply",
        update_frequency="ad_hoc",
        notes="Catalogo de benchmarks, historicos macro, comparacoes, deflatores e curva Tesouro.",
    ),
    "fixed_income": SourceMetadata(
        source_id="fixed_income",
        name="DadosBR Renda Fixa",
        base_url="local://dadosbr/fixed-income",
        license_name="Derived from official source licenses",
        update_frequency="ad_hoc",
        notes="Tesouro, credito privado publico, exposicao de fundos, fluxos, metricas e spreads.",
    ),
    "fundamentals": SourceMetadata(
        source_id="fundamentals",
        name="DadosBR Fundamentalistas",
        base_url="local://dadosbr/fundamentals",
        license_name="Derived from official source licenses; optional yfinance terms apply",
        update_frequency="ad_hoc",
        notes="Statements CVM canonicos, fatos financeiros, TTM, ratios, valuation e dividendos opcionais.",
    ),
    "corporate_actions": SourceMetadata(
        source_id="corporate_actions",
        name="DadosBR Proventos e Eventos Corporativos",
        base_url="local://dadosbr/corporate-actions",
        license_name="Derived from official source licenses; optional yfinance terms apply",
        update_frequency="ad_hoc",
        notes="Schema canonico de proventos, splits, subscricoes, fatores de ajuste e OHLCV ajustado.",
    ),
    "derivatives": SourceMetadata(
        source_id="derivatives",
        name="DadosBR Derivativos",
        base_url="local://dadosbr/derivatives",
        license_name="Derived from official source licenses",
        update_frequency="ad_hoc",
        notes="Contratos futuros, opcoes, ajustes, vencimentos, volume e open interest normalizados.",
    ),
    "interest_curves": SourceMetadata(
        source_id="interest_curves",
        name="DadosBR Curvas de Juros",
        base_url="local://dadosbr/curves",
        license_name="Derived from official source licenses",
        update_frequency="ad_hoc",
        notes="Curvas Tesouro, ANBIMA ETTJ normalizada, DI x Pre por futuros DI1, fatores e forwards.",
    ),
}


def get_source(source_id: str) -> SourceMetadata:
    return SOURCES[source_id]
